## Download the dataset 

**[Click here](https://www.kaggle.com/datasets/manishabhatt22/marketing-campaign-performance-dataset) to downlaod**

---

In [0]:
import pandas as pd

df = pd.read_csv("marketing_campaign_dataset.csv")
df.head()

   Campaign_ID              Company  ...     Customer_Segment        Date
0            1  Innovate Industries  ...    Health & Wellness  2021-01-01
1            2       NexGen Systems  ...         Fashionistas  2021-01-02
2            3    Alpha Innovations  ...  Outdoor Adventurers  2021-01-03
3            4   DataTech Solutions  ...    Health & Wellness  2021-01-04
4            5       NexGen Systems  ...    Health & Wellness  2021-01-05

[5 rows x 16 columns]

### Data Cleaning and Analysis

---

In [0]:
print(df.shape)
df.isna().sum()

(200000, 16)

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

In [0]:
# 1. Clean Acquisition_Cost: Remove '$' and ',' and convert to float
df['Acquisition_Cost'] = df['Acquisition_Cost'].replace('[\$,]', '', regex=True).astype(float)

# 2. Clean Date: Convert to datetime
df['Date'] = pd.to_datetime(df['Date'])

# 3. Verification: Check the types
print(df.info())

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/home/spark-1b352859-395c-4462-ba32-fb/.ipykernel/12491/command-6609824880280770-1256578809:2: SyntaxWarning: invalid escape sequence '\$'
  df['Acquisition_Cost'] = df['Acquisition_Cost'].replace('[\$,]', '', regex=True).astype(float)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  float64
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(4), object(8)
memory usage: 24.4+ MB
None

### Feature Engineering

---

In [0]:
# Create the calculated metrics
df['Total_Conversions'] = (df['Conversion_Rate'] * df['Clicks']).round(0)
df['Revenue'] = (df['ROI'] * df['Acquisition_Cost']) + df['Acquisition_Cost']
df['Net_Profit'] = df['Revenue'] - df['Acquisition_Cost']

# Check if the numbers look logical
print(df[['Acquisition_Cost', 'Revenue', 'Net_Profit', 'ROI']].head())

   Acquisition_Cost    Revenue  Net_Profit   ROI
0           16174.0  117908.46   101734.46  6.29
1           11566.0   76451.26    64885.26  5.61
2           10200.0   83436.00    73236.00  7.18
3           12724.0   83342.20    70618.20  5.55
4           16452.0  123390.00   106938.00  6.50

In [0]:
df.head()

   Campaign_ID              Company  ...    Revenue Net_Profit
0            1  Innovate Industries  ...  117908.46  101734.46
1            2       NexGen Systems  ...   76451.26   64885.26
2            3    Alpha Innovations  ...   83436.00   73236.00
3            4   DataTech Solutions  ...   83342.20   70618.20
4            5       NexGen Systems  ...  123390.00  106938.00

[5 rows x 19 columns]

### Checking whether the numerical cols have negative values or not

---

In [0]:
numerical_cols = df.select_dtypes(include='number').columns
negative_counts = (df[numerical_cols] < 0).sum()
display(negative_counts)

Campaign_ID          0
Conversion_Rate      0
Acquisition_Cost     0
ROI                  0
Clicks               0
Impressions          0
Engagement_Score     0
Total_Conversions    0
Revenue              0
Net_Profit           0
dtype: int64

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Campaign_ID        200000 non-null  int64
 1   Company            200000 non-null  object
 2   Campaign_Type      200000 non-null  object
 3   Target_Audience    200000 non-null  object
 4   Duration           200000 non-null  object
 5   Channel_Used       200000 non-null  object
 6   Conversion_Rate    200000 non-null  float64
 7   Acquisition_Cost   200000 non-null  float64
 8   ROI                200000 non-null  float64
 9   Location           200000 non-null  object
 10  Language           200000 non-null  object
 11  Clicks             200000 non-null  int64
 12  Impressions        200000 non-null  int64
 13  Engagement_Score   200000 non-null  int64
 14  Customer_Segment   200000 non-null  object
 15  Date               200000 non-null  datetime64[ns]
 16  Total_Conversions  200000 non-null  float64
 17  Revenue            200000 non-null  float64
 18  Net_Profit         200000 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(4), object(8)
memory usage: 29.0+ MB

### This is only for analysing the data. I created the full ETL Pipeline in DataBricks Platform. 

**You can check it out [here](https://dbc-4deb77d6-9b56.cloud.databricks.com/editor/files/640932635672237?o=7474658883336042)**.

---

#### I had also created the DashBoard for this on DataBricks. Check The Dashboard [here](https://dbc-4deb77d6-9b56.cloud.databricks.com/dashboardsv3/01f162606baa1e50824153f89b1b5197/published?o=7474658883336042).